### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by mayamehta0095** [EdoardoGruppi/AMLS_assignment20_21#2]
Thank you for Sharing your work

File "F:\maya\face-shape-detection\main.py", line 16, in <module>
    training_batches, valid_batches, test_batches = data_preprocessing(data_directory='face-shape-master',

  File "F:\maya\face-shape-detection\Modules\pre_processing.py", line 67, in data_preprocessing
    print(dataset_labels[dataset_labels[filename_column]])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")

KeyError: "None of [Index(['img_no_1.jpg', 'img_no_10.jpg', 'img_no_100.jpg', 'img_no_11.jpg',\n       'img_no_12.jpg', 'img_no_13.jpg', 'img_no_14.jpg', 'img_no_15.jpg',\n       'img_no_16.jpg', 'img_no_17.jpg',\n       ...\n       'img_no_391.jpg', 'img_no_392.jpg', 'img_no_393.jpg', 'img_no_394.jpg',\n       'img_no_395.jpg', 'img_no_396.jpg', 'img_no_397.jpg', 'img_no_398.jpg',\n       'img_no_399.jpg', 'img_no_400.jpg'],\n      dtype='object', length=400)] are in the [columns]"

I am having KeyError may be due to Dataset CSV file format 

![csv file](https://user-images.githubusercontent.com/76491209/145675235-1f83d396-aa7b-499e-8bf1-e695db142ac6.PNG)

Can you please guide me or share yor data set csv file format or suggest me something on this error?

**Comment by mayamehta0095** [comment]
I have included total 5 face shape type in one CSV file

**Comment by EdoardoGruppi** [comment]
The following is how the CSV file I used appears.

![image](https://user-images.githubusercontent.com/48513387/145709832-da546226-bb24-4ff8-9c86-96fc1c862174.png)

However, the problem is not in the Dataset CSV file format but in the print(dataset_labels[dataset_labels[filename_column]]) itself. I suppose you added this instruction just to debug the code and understand how the lines below work.

```python
random_test_list = sorted([dataset_labels[dataset_labels[filename_column] == i].index[0] for i in os.listdir(test_dir)])
```

In few words the idea is to get a sorted list of the indexes of all the images which have been moved before in the testing folder. An equivalent code snippet could be:  

```python
random_test_list = []
for item in os.listdir(test_dir):
    # Get the row which has the filename attribute equal to item
    row = dataset_labels[dataset_labels[filename_column] == item] 
    # The index property returns a list, even if the list contains a single element.
    random_test_list.append(row.index[0])
# Sort the list of values obtained
random_test_list = sorted(random_test_list)
print(random_test_list)
```

To conclude, the print instruction you executed was not functioning because you were trying to get all the columns of the dataframe with the names of the files. 

```python
# 1.
print(dataset_labels[['file_name', 'face_shape']])
# Returns
#      file_name face_shape
# 0        0.png          4
# 1        1.png          4

# 2 
print(dataset_labels[['103.png', '1.png']])
# Returns
# KeyError: "None of [Index(['103.png', '1.png'], dtype='object')] are in the [columns]"
```

If you have found my work and my reply useful please consider to star my project. It would mean a lot to me.

Best regards.

**Comment by mayamehta0095** [comment]
Thank you for your kind reply. I resolved that problem and train the module but having some other issue.
can you please guide me here as well
I attach screen shot for your reference.

![repo_err](https://user-images.githubusercontent.com/76491209/145787679-a7235dcd-c47b-43f2-942f-97cd32d60d11.PNG)

**Comment by mayamehta0095** [comment]
Here is training result
![1](https://user-images.githubusercontent.com/76491209/145787970-a5ca328c-67e3-480d-a1f8-be6076cc7a3f.PNG)

**Comment by mayamehta0095** [comment]
Where the weight file gets store after training?

**Comment by EdoardoGruppi** [comment]
I reckon the weights of the model are not saved throughout the execution of the code. I can be wrong as I have not run the project in a long time. However, you can always add specific lines in order to save and load the model as well as the weights.

Here some guides that can drive you along this process:

```
1. https://www.tensorflow.org/guide/keras/save_and_serialize
2. https://keras.io/api/models/model_saving_apis/
```

Specifically to the problem you encountered while training the architecture, make sure that the folders in your project are organised as I described in the "Main execution" section in the [Instructions.md](https://github.com/EdoardoGruppi/AMLS_assignment20_21/blob/main/Instructions.md) file. 

Also doublecheck that inside each created folder, 

![image](https://user-images.githubusercontent.com/48513387/145804198-b63245cc-6c66-40ba-be94-6af29f0967e1.png)

there is a labels.csv file containing the same filenames of the images stored in the corresponding **img** folder.


![image](https://user-images.githubusercontent.com/48513387/145804431-28dc2915-b65e-4e87-b4fe-3358d516c414.png)

It is likely that the issue is due to some conflicts between the names of the images as they appear in the folder **img** and in the related labels.csv file.

**Comment by mayamehta0095** [comment]
Thank you so much for your kind response.

Can you please give me some tips to achieve accuracy?

I am having different accuracy at training and testing i share results here
![res](https://user-images.githubusercontent.com/76491209/146130184-b24fb18c-abe8-47c3-bb79-91afa3a1b406.PNG)

**Comment by mayamehta0095** [comment]
I am using FastICA on images for pre-processing before training and same for testing as well

**Comment by EdoardoGruppi** [comment]
By comparing the results you have obtained during training and the validation/testing phases, I believe your results are afflicted by the overfitting issue. 

Overfitting occurs when a model fits exactly against its training data. In other words, it is as if the model has memorised how to work on the data included in the training dataset. This means that it has not really learnt the relationship that could exist between any input and its output. In fact, given a different input image (not seen during training), the result it returns is most likely not correct. In conclusion, the model is unable to generalize well from the training data to the unseen data.

The following articles and videos can help you to better understand the mentioned concepts and the possible solutions.
1. [The Problem Of Overfitting And How To Resolve It](https://medium.com/fintechexplained/the-problem-of-overfitting-and-how-to-resolve-it-1eb9456b1dfd)
2. [How to Handle Overfitting and Underfitting in Machine Learning](https://medium.datadriveninvestor.com/how-to-handle-overfitting-and-underfitting-470a1f7389fe)
3. [Overfitting and Underfitting: Visually Explained](https://towardsdatascience.com/overfitting-and-underfitting-visually-explained-like-youre-five-8a389b511751)
4. [Overfitting, Underfitting, and Model Capacity](https://www.youtube.com/watch?v=ms-Ooh9mjiE)
5. [Machine Learning Fundamentals: Bias and Variance](https://www.youtube.com/watch?v=EuBBz3bI-aA&t=326s)

Obviously, if you are looking for more detailed resources you can always find them on [Google Scholar](https://scholar.google.it/).

**Comment by mayamehta0095** [comment]
okay. Thank you so much
![image](https://user-images.githubusercontent.com/76491209/146171407-1da31968-9d55-40fa-bf96-68ce3fec4e12.png)
so this line should be smooth curve line if i am not getting wrong.

**Comment by EdoardoGruppi** [comment]
Not exactly. The smouthness of the learning curves depends on other factors including for example the amount of data the network works on before updating the weights. This means that, increasing the number of images before any network updates, it is likely that the movements of the line after every iteration would become more and more accentuated.

Your goal here should be to try to make the orange curve closer to the blue curve. For some reason, in fact, your model is not managing to do its job correctly on the pictures belonging to the validation set.

Finally, I would like to add that the network as well as the code presented in this project probably needs some changes if the task is performed on a dataset other than the Cartoon Dataset.

Moreover, in order to obtain satisfactory results, it is also of vital importance to use the correct quantity of images. In my case, as reported in the [introductory file](https://github.com/EdoardoGruppi/AMLS_assignment20_21#readme), I worked on 10,000 images of which 6000 dedicated to training, 2000 to the validation phase and 2000 to the testing step.
